[package]
name = "advent_of_code"
version = "0.8.0"
authors = ["Felix Sp√∂ttel <1682504+fspoettel@users.noreply.github.com>"]
edition = "2021"
default-run = "advent_of_code"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
md5 = "0.7.0"
pico-args = "0.5.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
